apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubernetes-dashboard
  name: dashboard-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: adminuser
subjects:
- kind: ServiceAccount
  name: adminuser